### PR TITLE
Derive Copy for types based on fixed-len arrays

### PR DESCRIPTION
**Pull request by oskin1**
Duplicate of #257

### CODE REVIEW

**Comment by oskin1** [comment]
@rooooooooob which version of clippy is used in by CI?

**Comment by rooooooooob** [comment]
I'm not sure why the CI job run is failing. I can't reproduce it locally with the same command, and the clippy error doesn't make much sense as both `PartialOrd`/`Ord` are derived, albeit using the `derivative` crate. There doesn't seem to be any new version of the `derivative` crate possibly causing different behavior between the CI task and locally.

Either way it's definitely not related to this PR as it's happening in my other open PR but the last few merged PRs had their CI jobs complete just fine.

**Comment by rooooooooob** [comment]
I put up a PR #269 that should fix it. I'll try and get it merged then rerun the check here and if it passes (it failing prevented a bunch of other later checks from running in this PR) I'll merge this.

**Comment by rooooooooob** [comment]
@oskin1 I think you'll need to merge the latest `develop` into your branch to have the CI get passed that issue. I tried just making the CI run again but it still fails. I would just LGTM it and merge it but it would be good to make sure that all the other tests in the CI pass.

**Comment by oskin1** [comment]
@rooooooooob rebased on top of develop

**Review by rooooooooob — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
